[ejs.app]
title = "Lapsus Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/ManucrackYT/LapsusLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaWebsiteURL = "https://lapsusdevs.tech/"
mediaYouTubeURL = "https://www.youtube.com/@LapsusDevelopment"
mediaDiscordURL = "https://discord.gg/yfrND8Rfg2"

[ejs.settings]
sourceGithubLink = "https://github.com/ManucrackYT/LapsusLauncher"
supportLink = "https://github.com/ManucrackYT/LapsusLauncher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to Lapsus Launcher"
welcomeDescription = "Get ready to start the adventure with the next generation Minecraft Launcher"
