[ejs.landing]
updateAvailableTooltip = "업데이트 가능"
usernamePlaceholder = "사용자 이름"
usernameEditButton = "수정"
settingsTooltip = "설정"
serverStatus = "서버"
serverStatusPlaceholder = "오프라인"
mojangStatus = "MOJANG 상태"
mojangStatusTooltipTitle = "서비스"
mojangStatusNETitle = "필수 아님"
newsButton = "뉴스"
launchButton = "실행"
launchButtonPlaceholder = "&#8226; 서버가 선택되지 않았습니다"
launchDetails = "잠시만 기다려 주세요.."
newsNavigationStatus = "{currentPage} / {totalPages}"
newsErrorLoadSpan = "뉴스 확인 중.."
newsErrorFailedSpan = "뉴스 불러오기 실패"
newsErrorRetryButton = "다시 시도"
newsErrorNoneSpan = "뉴스 없음"

[ejs.login]
loginCancelText = "취소"
loginSubheader = "오프라인 로그인"
loginEmailError = "* 사용자 이름은 최소 4자 이상이어야 합니다"
loginEmailPlaceholder = "사용자 이름"
loginPasswordError = "* 필수"
loginPasswordPlaceholder = "비밀번호"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "비밀번호를 잊으셨나요?"
loginRememberMeText = "자동 로그인"
loginButtonText = "로그인"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "계정이 필요하신가요?"
loginPasswordDisclaimer1 = "비밀번호는 Mojang으로 직접 전송되며 저장되지 않습니다."
loginPasswordDisclaimer2 = "{appName}은 Mojang AB와 제휴되어 있지 않습니다."

[ejs.loginOptions]
loginOptionsTitle = "로그인 옵션"
loginWithMicrosoft = "Microsoft로 로그인"
loginWithMojang = "오프라인 로그인"
cancelButton = "취소"

[ejs.overlay]
serverSelectHeader = "사용 가능한 서버"
serverSelectConfirm = "선택"
serverSelectCancel = "취소"
accountSelectHeader = "계정 선택"
accountSelectConfirm = "선택"
accountSelectCancel = "취소"

[ejs.settings]
navHeaderText = "설정"
navAccount = "계정"
navMinecraft = "마인크래프트"
navMods = "모드"
navJava = "Java"
navLauncher = "런처"
navAbout = "정보"
navUpdates = "업데이트"
navDone = "완료"
tabAccountHeaderText = "계정 설정"
tabAccountHeaderDesc = "새 계정을 추가하거나 기존 계정을 관리합니다."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Microsoft 계정 추가"
mojangAccount = "오프라인"
addMojangAccount = "+ 오프라인 계정 추가"
minecraftTabHeaderText = "마인크래프트 설정"
minecraftTabHeaderDesc = "게임 실행 관련 옵션."
gameResolutionTitle = "게임 해상도"
launchFullscreenTitle = "전체 화면으로 실행"
autoConnectTitle = "실행 시 서버에 자동 접속"
launchDetachedTitle = "런처와 분리된 게임 프로세스로 실행"
launchDetachedDesc = "게임이 분리되지 않으면 런처를 닫을 때 게임도 함께 종료됩니다."
tabModsHeaderText = "모드 설정"
tabModsHeaderDesc = "모드 활성화 또는 비활성화"
switchServerButton = "서버 전환"
requiredMods = "필수 모드"
optionalMods = "선택 모드"
dropinMods = "드롭인 모드"
addMods = "모드 추가"
dropinRefreshNote = "(새로고침하려면 F5)"
shaderpacks = "셰이더팩"
shaderpackDesc = "셰이더를 활성화하거나 비활성화합니다. 주의: 셰이더는 고사양 환경에서만 원활히 작동합니다. 여기서 사용자 지정 팩을 추가할 수 있습니다."
selectShaderpack = "셰이더팩 선택"
tabJavaHeaderText = "Java 설정"
tabJavaHeaderDesc = "Java 구성 관리 (고급)"
memoryTitle = "메모리"
maxRAM = "최대 RAM"
minRAM = "최소 RAM"
memoryDesc = "권장 최소 RAM은 3GB입니다. 최소 및 최대 값을 동일하게 설정하면 지연이 줄어들 수 있습니다."
memoryTotalTitle = "총합"
memoryAvailableTitle = "사용 가능"
javaExecutableTitle = "Java 실행 파일"
javaExecSelDialogTitle = "Java 실행 파일 선택"
javaExecSelButtonText = "파일 선택"
javaExecDesc = "Java 실행 파일은 게임 실행 전 검증됩니다."
javaPathDesc = "경로는 <strong>{pathSuffix}</strong>로 끝나야 합니다."
jvmOptsTitle = "추가 JVM 옵션"
jvmOptsDesc = "런타임에 JVM에 제공할 옵션. <em>-Xms</em> 및 <em>-Xmx</em>는 포함하지 마세요."
launcherTabHeaderText = "런처 설정"
launcherTabHeaderDesc = "런처 자체 관련 옵션"
allowPrereleaseTitle = "사전 릴리스 업데이트 허용"
allowPrereleaseDesc = "사전 릴리스에는 아직 완전히 테스트되지 않은 새로운 기능이 포함될 수 있습니다.<br>사전 릴리스 버전을 사용하는 경우 항상 적용됩니다."
dataDirectoryTitle = "데이터 디렉터리"
selectDataDirectory = "데이터 디렉터리 선택"
chooseFolder = "폴더 선택"
dataDirectoryDesc = "모든 게임 파일 및 로컬 Java 설치가 데이터 디렉터리에 저장됩니다.<br>스크린샷 및 월드 저장은 해당 서버 설정의 인스턴스 폴더에 저장됩니다."
aboutTabHeaderText = "정보"
aboutTabHeaderDesc = "현재 버전에 대한 정보 및 릴리스 노트를 확인합니다."
aboutTitle = "{appName}"
stableRelease = "안정 버전"
versionText = "버전 "
sourceGithub = "소스 (GitHub)"
support = "지원"
devToolsConsole = "개발자 도구 콘솔"
releaseNotes = "릴리스 노트"
changelog = "변경 로그"
noReleaseNotes = "릴리스 노트 없음"
viewReleaseNotes = "GitHub에서 릴리스 노트 보기"
launcherUpdatesHeaderText = "런처 업데이트"
launcherUpdatesHeaderDesc = "런처의 업데이트를 다운로드, 설치 및 검토합니다."
checkForUpdates = "업데이트 확인"
whatsNew = "새로운 기능"
updateReleaseNotes = "업데이트 릴리스 노트"

[ejs.waiting]
waitingText = "Microsoft를 기다리는 중.."

[ejs.welcome]
continueButton = "계속"

[js.login]
login = "로그인"
loggingIn = "로그인 중"
success = "성공"
tryAgain = "다시 시도"

[js.login.error]
invalidValue = "* 사용자 이름은 최소 4자 이상이어야 합니다"
requiredValue = "* 필수"

[js.login.error.unknown]
title = "로그인 중 알 수 없는 오류"
desc = "알 수 없는 오류가 발생했습니다. 자세한 내용은 콘솔을 확인하세요."

[js.landing.launch]
pleaseWait = "잠시만 기다려 주세요.."
failureTitle = "실행 중 오류"
failureText = "자세한 내용은 콘솔 (CTRL + Shift + i)을 확인하세요."
okay = "확인"

[js.landing.selectedAccount]
noAccountSelected = "선택된 계정 없음"

[js.landing.selectedServer]
noSelection = "선택된 서버 없음"
loading = "불러오는 중.."

[js.landing.serverStatus]
server = "서버"
offline = "오프라인"
players = "플레이어"

[js.landing.systemScan]
checking = "시스템 정보 확인 중.."
noCompatibleJava = "호환되는<br>Java 설치를 찾을 수 없음"
installJavaMessage = "Minecraft를 실행하려면 Java {major}의 64비트 설치가 필요합니다. 설치하시겠습니까?"
installJava = "Java 설치"
installJavaManually = "직접 설치"
javaDownloadPrepare = "Java 다운로드 준비 중.."
javaDownloadFailureTitle = "Java 다운로드 오류"
javaDownloadFailureText = "자세한 내용은 콘솔 (CTRL + Shift + i)을 확인하세요."
javaRequired = "Java 필요<br>실행하려면"
javaRequiredMessage = "유효한 x64 Java {major} 설치가 필요합니다.<br>"
javaRequiredDismiss = "이해했습니다"
javaRequiredCancel = "뒤로 가기"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK 배포판을 찾지 못했습니다."
javaDownloadCorruptedError = "다운로드된 JDK의 해시가 잘못되었습니다. 파일이 손상되었을 수 있습니다."
extractingJava = "Java 추출 중"
javaInstalled = "Java 설치 완료!"

[js.landing.dlAsync]
loadingServerInfo = "서버 정보 불러오는 중.."
fatalError = "치명적 오류"
unableToLoadDistributionIndex = "배포 인덱스를 불러올 수 없습니다. 자세한 내용은 콘솔 (CTRL + Shift + i)을 확인하세요."
pleaseWait = "잠시만 기다려 주세요.."
errorDuringLaunchTitle = "실행 중 오류"
seeConsoleForDetails = "자세한 내용은 콘솔 (CTRL + Shift + i)을 확인하세요."
validatingFileIntegrity = "파일 무결성 확인 중.."
errorDuringFileVerificationTitle = "파일 검증 중 오류"
downloadingFiles = "파일 다운로드 중.."
errorDuringFileDownloadTitle = "파일 다운로드 중 오류"
preparingToLaunch = "실행 준비 중.."
launchingGame = "게임 실행 중.."
launchWrapperNotDownloaded = "메인 파일 LaunchWrapper 다운로드에 실패했습니다. 그 결과, 게임을 실행할 수 없습니다.<br><br>이 문제를 해결하려면 백신 프로그램을 일시적으로 끄고 게임을 다시 실행하세요.<br><br>시간이 되신다면 <a href=\"https://github.com/ManucrackYT/LapsusLauncher/issues\">문제를 보고</a> 어떤 백신 소프트웨어를 사용하는지 알려주세요. 저희가 업체에 연락하여 문제 해결을 시도하겠습니다."
doneEnjoyGame = "완료. 게임을 즐기세요!"
checkConsoleForDetails = "자세한 내용은 콘솔 (CTRL + Shift + i)을 확인하세요."

[js.landing.news]
checking = "뉴스 확인 중"

[js.settings.fileSelectors]
executables = "실행 파일"
allFiles = "모든 파일"

[js.settings.mstfLogin]
errorTitle = "문제가 발생했습니다"
errorMessage = "Microsoft 인증에 실패했습니다. 다시 시도하세요."
okButton = "확인"

[js.settings.mstfLogout]
errorTitle = "문제가 발생했습니다"
errorMessage = "Microsoft 로그아웃에 실패했습니다. 다시 시도하세요."
okButton = "확인"

[js.settings.authAccountSelect]
selectButton = "계정 선택"
selectedButton = "선택된 계정 &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "경고<br>이것은 마지막 계정입니다"
lastAccountWarningMessage = "런처를 사용하려면 최소 하나의 계정에 로그인되어 있어야 합니다. 이후 다시 로그인해야 합니다.<br><br>정말 로그아웃하시겠습니까?"
confirmButton = "확실합니다"
cancelButton = "취소"

[js.settings.authAccountPopulate]
username = "사용자 이름"
uuid = "UUID"
selectAccount = "계정 선택"
selectedAccount = "선택된 계정 ✓"
logout = "로그아웃"

[js.settings.dropinMods]
removeButton = "제거"
deleteFailedTitle = "드롭인 모드 {fullName} 삭제 실패"
deleteFailedMessage = "파일이 사용 중이지 않은지 확인하고 다시 시도하세요."
failedToggleTitle = "하나 이상의 드롭인 모드를 전환하지 못했습니다"
okButton = "확인"

[js.settings.serverListing]
mainServer = "메인 서버"

[js.settings.java]
selectedJava = "선택됨: Java {version} ({vendor})"
invalidSelection = "잘못된 선택"
requiresJava = "Java {major} x64 필요"
availableOptions = "Java {major} (HotSpot VM)의 사용 가능한 옵션"

[js.settings.about]
preReleaseTitle = "사전 릴리스"
stableReleaseTitle = "안정 버전"
releaseNotesFailed = "릴리스 노트 불러오기 실패"

[js.settings.updates]
newReleaseTitle = "새 릴리스 사용 가능"
newPreReleaseTitle = "새 사전 릴리스 사용 가능"
downloadingButton = "다운로드 중.."
downloadButton = 'GitHub에서 다운로드<span style="font-size: 10px;color: gray;text-shadow: none !important;">런처를 닫고 dmg 파일을 실행하여 업데이트하세요.</span>'
latestVersionTitle = "최신 버전을 사용 중입니다"
checkForUpdatesButton = "업데이트 확인"
checkingForUpdatesButton = "업데이트 확인 중.."

[js.uibinder.startup]
fatalErrorTitle = "치명적 오류: 배포 인덱스를 불러올 수 없음"
fatalErrorMessage = "배포 인덱스를 다운로드하기 위해 서버에 연결할 수 없었습니다. 불러올 로컬 사본도 없습니다.<br><br>배포 인덱스는 최신 서버 정보를 제공하는 필수 파일입니다. 이 파일 없이는 런처를 시작할 수 없습니다. 인터넷에 연결되어 있는지 확인한 후 애플리케이션을 다시 실행하세요."
closeButton = "닫기"

[js.uibinder.validateAccount]
failedMessageTitle = "로그인 새로 고침 실패"
failedMessage = "<strong>{account}</strong>의 로그인을 새로 고칠 수 없습니다. 다른 계정을 선택하거나 다시 로그인하세요."
failedMessageSelectAnotherAccount = "<strong>{account}</strong>의 로그인을 새로 고칠 수 없습니다. 다시 로그인하세요."
loginButton = "로그인"
selectAnotherAccountButton = "다른 계정 선택"

[js.uicore.autoUpdate]
checkingForUpdateButton = "업데이트 확인 중..."
installNowButton = "지금 설치"
checkForUpdatesButton = "업데이트 확인"
