[ejs.landing]
updateAvailableTooltip = "Atualização Disponível"
usernamePlaceholder = "Nome de Usuário"
usernameEditButton = "Editar"
settingsTooltip = "Configurações"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "STATUS MOJANG"
mojangStatusTooltipTitle = "Serviços"
mojangStatusNETitle = "Não&nbsp;Essencial"
newsButton = "NOTÍCIAS"
launchButton = "JOGAR"
launchButtonPlaceholder = "&#8226; Nenhum Servidor Selecionado"
launchDetails = "Por favor, aguarde.."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Verificando notícias.."
newsErrorFailedSpan = "Falha ao carregar notícias"
newsErrorRetryButton = "Tentar Novamente"
newsErrorNoneSpan = "Nenhuma notícia"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "LOGIN OFFLINE"
loginEmailError = "* Seu nome de usuário deve ter pelo menos 4 caracteres"
loginEmailPlaceholder = "Seu Nome de Usuário"
loginPasswordError = "* Obrigatório"
loginPasswordPlaceholder = "SENHA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "esqueceu a senha?"
loginRememberMeText = "lembrar de mim?"
loginButtonText = "ENTRAR"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Precisa de uma conta?"
loginPasswordDisclaimer1 = "Sua senha é enviada diretamente para a Mojang e nunca é armazenada."
loginPasswordDisclaimer2 = "{appName} não é afiliado à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opções de Login"
loginWithMicrosoft = "Entrar com Microsoft"
loginWithMojang = "Entrar Offline"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores Disponíveis"
serverSelectConfirm = "Selecionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Selecionar uma Conta"
accountSelectConfirm = "Selecionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configurações"
navAccount = "Conta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Sobre"
navUpdates = "Atualizações"
navDone = "Concluído"
tabAccountHeaderText = "Configurações da Conta"
tabAccountHeaderDesc = "Adicione novas contas ou gerencie as existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Adicionar Conta Microsoft"
mojangAccount = "Offline"
addMojangAccount = "+ Adicionar Conta Offline"
minecraftTabHeaderText = "Configurações do Minecraft"
minecraftTabHeaderDesc = "Opções relacionadas ao lançamento do jogo."
gameResolutionTitle = "Resolução do Jogo"
launchFullscreenTitle = "Iniciar em tela cheia."
autoConnectTitle = "Conectar automaticamente ao servidor ao iniciar."
launchDetachedTitle = "Iniciar processo do jogo separado do launcher."
launchDetachedDesc = "Se o jogo não estiver separado, fechar o launcher também fechará o jogo."
tabModsHeaderText = "Configurações de Mods"
tabModsHeaderDesc = "Ative ou desative mods."
switchServerButton = "Trocar"
requiredMods = "Mods Obrigatórios"
optionalMods = "Mods Opcionais"
dropinMods = "Mods Adicionados"
addMods = "Adicionar Mods"
dropinRefreshNote = "(F5 para Atualizar)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Ative ou desative shaders. Atenção: os shaders só funcionam bem em setups potentes. Você pode adicionar pacotes personalizados aqui."
selectShaderpack = "Selecionar Shaderpack"
tabJavaHeaderText = "Configurações do Java"
tabJavaHeaderDesc = "Gerencie a configuração do Java (avançado)."
memoryTitle = "Memória"
maxRAM = "RAM Máxima"
minRAM = "RAM Mínima"
memoryDesc = "O mínimo recomendado de RAM é 3 gigabytes. Definir os valores mínimo e máximo iguais pode reduzir o lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponível"
javaExecutableTitle = "Executável do Java"
javaExecSelDialogTitle = "Selecionar Executável Java"
javaExecSelButtonText = "Escolher Arquivo"
javaExecDesc = "O executável Java é validado antes do lançamento do jogo."
javaPathDesc = "O caminho deve terminar com <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opções Adicionais da JVM"
jvmOptsDesc = "Opções fornecidas à JVM em tempo de execução. <em>-Xms</em> e <em>-Xmx</em> não devem ser incluídas."
launcherTabHeaderText = "Configurações do Launcher"
launcherTabHeaderDesc = "Opções relacionadas ao próprio launcher."
allowPrereleaseTitle = "Permitir Atualizações Pré-Lançamento."
allowPrereleaseDesc = "As Pré-Lançamentos incluem novos recursos que podem não ter sido totalmente testados ou integrados.<br>Isso sempre será verdade se você estiver usando uma versão pré-lançamento."
dataDirectoryTitle = "Diretório de Dados"
selectDataDirectory = "Selecionar Diretório de Dados"
chooseFolder = "Escolher Pasta"
dataDirectoryDesc = "Todos os arquivos do jogo e instalações locais do Java serão armazenados no diretório de dados.<br>Capturas de tela e mundos salvos são armazenados na pasta da instância para a configuração do servidor correspondente."
aboutTabHeaderText = "Sobre"
aboutTabHeaderDesc = "Veja informações e notas de versão da versão atual."
aboutTitle = "{appName}"
stableRelease = "Versão Estável"
versionText = "Versão "
sourceGithub = "Código-Fonte (GitHub)"
support = "Suporte"
devToolsConsole = "Console DevTools"
releaseNotes = "Notas de Versão"
changelog = "Registro de Alterações"
noReleaseNotes = "Sem Notas de Versão"
viewReleaseNotes = "Ver Notas no GitHub"
launcherUpdatesHeaderText = "Atualizações do Launcher"
launcherUpdatesHeaderDesc = "Baixe, instale e revise as atualizações do launcher."
checkForUpdates = "Verificar Atualizações"
whatsNew = "Novidades"
updateReleaseNotes = "Notas da Atualização"

[ejs.waiting]
waitingText = "Aguardando Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"


[js.login]
login = "ENTRAR"
loggingIn = "ENTRANDO"
success = "SUCESSO"
tryAgain = "Tentar Novamente"

[js.login.error]
invalidValue = "* Seu nome de usuário deve ter pelo menos 4 caracteres"
requiredValue = "* Obrigatório"

[js.login.error.unknown]
title = "Erro Desconhecido Durante Login"
desc = "Ocorreu um erro desconhecido. Veja o console para detalhes."

[js.landing.launch]
pleaseWait = "Por favor, aguarde.."
failureTitle = "Erro Durante o Lançamento"
failureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
okay = "Ok"

[js.landing.selectedAccount]
noAccountSelected = "Nenhuma Conta Selecionada"

[js.landing.selectedServer]
noSelection = "Nenhum Servidor Selecionado"
loading = "Carregando.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "OFFLINE"
players = "JOGADORES"

[js.landing.systemScan]
checking = "Verificando informações do sistema.."
noCompatibleJava = "Nenhuma Instalação<br>Compatível do Java Encontrada"
installJavaMessage = "Para iniciar o Minecraft, você precisa de uma instalação 64 bits do Java {major}. Deseja que instalemos uma cópia?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando Download do Java.."
javaDownloadFailureTitle = "Erro Durante o Download do Java"
javaDownloadFailureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
javaRequired = "Java é Necessário<br>para Iniciar"
javaRequiredMessage = 'Uma instalação válida x64 do Java {major} é necessária para iniciar.<br>'
javaRequiredDismiss = "Entendi"
javaRequiredCancel = "Voltar"

[js.landing.downloadJava]
findJdkFailure = "Falha ao encontrar distribuição OpenJDK."
javaDownloadCorruptedError = "O JDK baixado tem um hash inválido, o arquivo pode estar corrompido."
extractingJava = "Extraindo Java"
javaInstalled = "Java Instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Carregando informações do servidor.."
fatalError = "Erro Fatal"
unableToLoadDistributionIndex = "Não foi possível carregar uma cópia do índice de distribuição. Veja o console (CTRL + Shift + i) para mais detalhes."
pleaseWait = "Por favor, aguarde.."
errorDuringLaunchTitle = "Erro Durante o Lançamento"
seeConsoleForDetails = "Veja o console (CTRL + Shift + i) para mais detalhes."
validatingFileIntegrity = "Validando integridade dos arquivos.."
errorDuringFileVerificationTitle = "Erro Durante Verificação de Arquivos"
downloadingFiles = "Baixando arquivos.."
errorDuringFileDownloadTitle = "Erro Durante o Download de Arquivos"
preparingToLaunch = "Preparando para iniciar.."
launchingGame = "Iniciando jogo.."
launchWrapperNotDownloaded = "O arquivo principal, LaunchWrapper, não foi baixado corretamente. Como resultado, o jogo não pode iniciar.<br><br>Para corrigir isso, desative temporariamente seu antivírus e inicie o jogo novamente.<br><br>Se possível, por favor <a href=\"https://github.com/ManucrackYT/LapsusLauncher/issues\">abra um issue</a> e nos diga qual antivírus você usa. Nós entraremos em contato com eles para resolver a situação."
doneEnjoyGame = "Concluído. Aproveite o jogo!"
checkConsoleForDetails = "Por favor, verifique o console (CTRL + Shift + i) para mais detalhes."

[js.landing.news]
checking = "Verificando notícias"

[js.settings.fileSelectors]
executables = "Executáveis"
allFiles = "Todos os Arquivos"

[js.settings.mstfLogin]
errorTitle = "Algo Deu Errado"
errorMessage = "A autenticação Microsoft falhou. Tente novamente."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Algo Deu Errado"
errorMessage = "Falha ao sair da Microsoft. Tente novamente."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Selecionar Conta"
selectedButton = "Conta Selecionada &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Atenção<br>Esta é Sua Última Conta"
lastAccountWarningMessage = "Para usar o launcher você precisa estar logado em pelo menos uma conta. Será necessário entrar novamente depois.<br><br>Tem certeza de que deseja sair?"
confirmButton = "Tenho Certeza"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Nome de Usuário"
uuid = "UUID"
selectAccount = "Selecionar Conta"
selectedAccount = "Conta Selecionada ✓"
logout = "Sair"

[js.settings.dropinMods]
removeButton = "Remover"
deleteFailedTitle = "Falha ao Excluir<br>Mod {fullName}"
deleteFailedMessage = "Verifique se o arquivo não está em uso e tente novamente."
failedToggleTitle = "Falha ao Alternar<br>Um ou Mais Mods"
okButton = "Ok"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Selecionado: Java {version} ({vendor})"
invalidSelection = "Seleção Inválida"
requiresJava = "Requer Java {major} x64."
availableOptions = "Opções Disponíveis para Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-lançamento"
stableReleaseTitle = "Versão Estável"
releaseNotesFailed = "Falha ao carregar notas de versão."

[js.settings.updates]
newReleaseTitle = "Nova Versão Disponível"
newPreReleaseTitle = "Novo Pré-lançamento Disponível"
downloadingButton = "Baixando.."
downloadButton = 'Baixar do GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Feche o launcher e execute o dmg para atualizar.</span>'
latestVersionTitle = "Você está usando a versão mais recente"
checkForUpdatesButton = "Verificar Atualizações"
checkingForUpdatesButton = "Verificando Atualizações.."

[js.uibinder.startup]
fatalErrorTitle = "Erro Fatal: Não Foi Possível Carregar Índice de Distribuição"
fatalErrorMessage = "Não foi possível estabelecer uma conexão com nossos servidores para baixar o índice de distribuição. Nenhuma cópia local estava disponível para carregar. <br><br>O índice de distribuição é um arquivo essencial que fornece as informações mais recentes do servidor. O launcher não pode iniciar sem ele. Certifique-se de estar conectado à internet e reinicie o aplicativo."
closeButton = "Fechar"

[js.uibinder.validateAccount]
failedMessageTitle = "Falha ao Atualizar Login"
failedMessage = "Não foi possível atualizar o login de <strong>{account}</strong>. Selecione outra conta ou faça login novamente."
failedMessageSelectAnotherAccount = "Não foi possível atualizar o login de <strong>{account}</strong>. Faça login novamente."
loginButton = "Entrar"
selectAnotherAccountButton = "Selecionar Outra Conta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Verificando Atualizações..."
installNowButton = "Instalar Agora"
checkForUpdatesButton = "Verificar Atualizações"
